apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce # Solo puede ser montado por un nodo a la vez
  resources:
    requests:
      storage: 2Gi
