apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: Y2xhdmUxMjM0
  MYSQL_DATABASE: ZGJfYXBpX3NlcnZpY2U=
  MYSQL_ROOT_PASSWORD: Y2xhdmUxMjM0
