apiVersion: v1
kind: Service
metadata:
  name: mysql-service # DB_HOST para api-service en Kubernetes
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
