apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-project-app.fullname" . }}-api-service
  labels:
    {{- include "demo-project-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-service
spec:
  selector:
    {{- include "demo-project-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP