apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "demo-project-app.fullname" . }}-mysql-pv-claim
  labels:
    {{- include "demo-project-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storageSize }}