apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-project-app.fullname" . }}-mysql-credentials
  labels:
    {{- include "demo-project-app.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_USER: {{ .Values.mysql.user | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc | quote }}
