# Default values for nodejs-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1 # Default replica count for both api and frontend

imagePullSecrets:
  - name: ghcr-secret # Tu secret de GHCR que ya creaste en K8s

# Configuracion para MySQL
mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  user: user
  password: password
  database: mydatabase
  rootPassword: root_password
  storageSize: 2Gi # Tamaño del PVC
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Configuracion para API Service
apiService:
  replicaCount: 1
  image:
    repository: ghcr.io/camilogh/ci_cd_project_demo/api-service
    tag: "latest" # O el tag específico de tu imagen
    pullPolicy: IfNotPresent
  nodeEnv: production
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 150m
      memory: 192Mi

# Configuracion para Frontend Service
frontendService:
  replicaCount: 1
  image:
    repository: ghcr.io/camilogh/ci_cd_project_demo/frontend-service
    tag: "latest" # O el tag específico de tu imagen
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
    serviceType: LoadBalancer
# Ingress configuration (opcional si usas ingress para frontend)
# ingress:
#   enabled: false
#   className: ""
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: chart-example.local
#       paths:
#         - path: /
#           pathType: ImplementationSpecific
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local
